name: Deploy to Server

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: Deploy changes to server
      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no root@77.37.47.53<< EOF  
          
           export PATH="/root/.nvm/versions/node/v20.15.0/bin:$PATH" # Add Node.js binary explicitly
          echo "PATH: $PATH"
          which node || { echo "Node.js binary not found in PATH!"; exit 1; }
          node -v || { echo "Node.js is not installed!"; exit 1; }
          which pnpm || { echo "pnpm binary not found in PATH!"; exit 1; }
          pnpm -v || { echo "pnpm is not installed!"; exit 1; }

          
           cd /root/enteBuddy-ecommerce/
            echo $PATH
            # Pull the latest changes
            git pull origin main

            # Step 1: Build the Client (Frontend)
            cd client 
            which node
            
            install pnpm
            pnpm  build 
          
            rm -rf /var/www/enteBuddy-ecommerce/client/dist/*
            cp -r  /root/enteBuddy-ecommerce/client/dist/*  /var/www/enteBuddy-ecommerce/client/dist/

            # Step 2: Update the Server (Backend)
            cd ../
            pnpm install
            # Step 3: Restart services
            pm2 restart all
            sudo systemctl restart nginx
          EOF
