name: Deploy to Server

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: Deploy changes to server
      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no root@77.37.47.53<< EOF
           cd /root/enteBuddy-ecommerce/

            # Pull the latest changes
            git pull origin main

            # Step 1: Build the Client (Frontend)
            cd client
            pnpm  build 
            mkdir /root/hello-kitty
            rm -rf /var/www/enteBuddy-ecommerce/client/dist/*
            cp -r  /root/enteBuddy-ecommerce/client/dist/*  /var/www/enteBuddy-ecommerce/client/

            # Step 2: Update the Server (Backend)
            cd ../
            pnpm install
            cp -r public /var/www/enteBuddy-ecommerce/server/public

            # Step 3: Restart services
            pm2 restart all
            sudo systemctl restart nginx
          EOF
